services:
  postgres:
    image: postgres:15-alpine
    container_name: examforge_postgres

    environment:
      POSTGRES_DB: Exame_forgeDB
      POSTGRES_USER: aniket
      POSTGRES_PASSWORD: admin123

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: examforge_redis

    ports:
      - "6479:6379"

    volumes:
      - redis_data:/data

    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: examforge_qdrant

    ports:
      - "6433:6333"
      - "6434:6334"

    volumes:
      - qdrant_data:/qdrant/storage

    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
  qdrant_data: