version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dev.Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=Exame_forgeDB
      - DB_USER=aniket
      - DB_PASSWORD=admin123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
