apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Aptora.fullname" . }}-backend
  labels:
    app: {{ include "Aptora.name" . }}-backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ include "Aptora.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "Aptora.name" . }}-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/backend:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.backendPort }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ include "Aptora.fullname" . }}-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "Aptora.fullname" . }}-secret
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "Aptora.fullname" . }}-secret
              key: SECRET_KEY
        resources:
          {{- toYaml .Values.resources.backend | nindent 10 }}
