apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Aptora.fullname" . }}-frontend
  labels:
    app: {{ include "Aptora.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "Aptora.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "Aptora.name" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/frontend:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.frontendPort }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ include "Aptora.fullname" . }}-config
        resources:
          {{- toYaml .Values.resources.frontend | nindent 10 }}
