{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "Aptora.fullname" . }}
  labels:
    app: {{ include "Aptora.name" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "Aptora.fullname" $ }}-{{ .serviceName }}
            port:
              number: {{ if eq .serviceName "backend" }}{{ $.Values.service.backendPort }}{{ else }}{{ $.Values.service.frontendPort }}{{ end }}
      {{- end }}
  {{- end }}
{{- end }}
