apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Aptora.fullname" . }}-secret
type: Opaque
data:
  DB_PASSWORD: {{ default "cGFzc3dvcmQxMjM=" .Values.config.dbPassword | quote }}
  SECRET_KEY: {{ default "Y2ktdGVzdC1zZWNyZXQ=" .Values.config.secretKey | quote }}
