apiVersion: v1
kind: Secret
metadata:
  name: Aptora-secret
  namespace: Aptora
type: Opaque
data:
  # Base64 encoded values. Example values shown below.
  # postgres admin password: password123
  DB_PASSWORD: "cGFzc3dvcmQxMjM="
  # backend secret key: ci-test-secret
  SECRET_KEY: "Y2ktdGVzdC1zZWNyZXQ="
