"""initial_schema

Revision ID: c3d0ac5ca41e
Revises: 
Create Date: 2026-07-19 19:17:31.558969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d0ac5ca41e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('account_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_deletion_requests_id'), 'account_deletion_requests', ['id'], unique=False)
    op.create_table('goal_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_exam', sa.String(length=150), nullable=False),
    sa.Column('exam_category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_workspaces_id'), 'goal_workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_goal_workspaces_user_id'), 'goal_workspaces', ['user_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('cycle', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('txn_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_txn_id'), 'orders', ['txn_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('college', sa.String(length=150), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('mock_average', sa.Float(), nullable=True),
    sa.Column('questions_solved', sa.Integer(), nullable=True),
    sa.Column('study_hours_total', sa.Float(), nullable=True),
    sa.Column('completion_pct', sa.Float(), nullable=True),
    sa.Column('bookmarks_count', sa.Integer(), nullable=True),
    sa.Column('certificates_count', sa.Integer(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('connected_devices', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('plan_renewal', sa.String(length=30), nullable=True),
    sa.Column('ai_credits', sa.Integer(), nullable=True),
    sa.Column('storage_used_mb', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('gap_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['goal_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'subject', name='uq_workspace_subject')
    )
    op.create_index(op.f('ix_gap_analysis_id'), 'gap_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_workspace_id'), 'gap_analysis', ['workspace_id'], unique=False)
    op.create_table('goal_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('daily_study_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['goal_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_timelines_id'), 'goal_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_goal_timelines_workspace_id'), 'goal_timelines', ['workspace_id'], unique=True)
    op.create_table('learning_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('learning_mode', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['goal_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'learning_mode', name='uq_workspace_learning_mode')
    )
    op.create_index(op.f('ix_learning_modes_id'), 'learning_modes', ['id'], unique=False)
    op.create_index(op.f('ix_learning_modes_workspace_id'), 'learning_modes', ['workspace_id'], unique=False)
    op.create_table('study_lifestyles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('preferred_device', sa.String(length=100), nullable=False),
    sa.Column('learning_environment', sa.String(length=100), nullable=False),
    sa.Column('internet_availability', sa.String(length=100), nullable=False),
    sa.Column('consistency_commit', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['goal_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_lifestyles_id'), 'study_lifestyles', ['id'], unique=False)
    op.create_index(op.f('ix_study_lifestyles_workspace_id'), 'study_lifestyles', ['workspace_id'], unique=True)
    op.create_table('user_onboarding_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('stream', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('syllabus_percent', sa.Integer(), nullable=True),
    sa.Column('current_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['goal_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_profiles_id'), 'user_onboarding_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_onboarding_profiles_workspace_id'), 'user_onboarding_profiles', ['workspace_id'], unique=True)
    op.create_table('study_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifestyle_id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lifestyle_id'], ['study_lifestyles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lifestyle_id', 'time_slot', name='uq_lifestyle_time_slot')
    )
    op.create_index(op.f('ix_study_time_slots_id'), 'study_time_slots', ['id'], unique=False)
    op.create_index(op.f('ix_study_time_slots_lifestyle_id'), 'study_time_slots', ['lifestyle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_time_slots_lifestyle_id'), table_name='study_time_slots')
    op.drop_index(op.f('ix_study_time_slots_id'), table_name='study_time_slots')
    op.drop_table('study_time_slots')
    op.drop_index(op.f('ix_user_onboarding_profiles_workspace_id'), table_name='user_onboarding_profiles')
    op.drop_index(op.f('ix_user_onboarding_profiles_id'), table_name='user_onboarding_profiles')
    op.drop_table('user_onboarding_profiles')
    op.drop_index(op.f('ix_study_lifestyles_workspace_id'), table_name='study_lifestyles')
    op.drop_index(op.f('ix_study_lifestyles_id'), table_name='study_lifestyles')
    op.drop_table('study_lifestyles')
    op.drop_index(op.f('ix_learning_modes_workspace_id'), table_name='learning_modes')
    op.drop_index(op.f('ix_learning_modes_id'), table_name='learning_modes')
    op.drop_table('learning_modes')
    op.drop_index(op.f('ix_goal_timelines_workspace_id'), table_name='goal_timelines')
    op.drop_index(op.f('ix_goal_timelines_id'), table_name='goal_timelines')
    op.drop_table('goal_timelines')
    op.drop_index(op.f('ix_gap_analysis_workspace_id'), table_name='gap_analysis')
    op.drop_index(op.f('ix_gap_analysis_id'), table_name='gap_analysis')
    op.drop_table('gap_analysis')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_orders_txn_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_goal_workspaces_user_id'), table_name='goal_workspaces')
    op.drop_index(op.f('ix_goal_workspaces_id'), table_name='goal_workspaces')
    op.drop_table('goal_workspaces')
    op.drop_index(op.f('ix_account_deletion_requests_id'), table_name='account_deletion_requests')
    op.drop_table('account_deletion_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
