"use client";

import { motion } from "framer-motion";
import {
  FileCheck,
  ShieldCheck,
  UserCog,
  Lock,
  AlertTriangle,
  RefreshCw,
} from "lucide-react";
import PageLayout from "@/components/layout/PageLayout";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

const sections = [
  {
    number: "01",
    icon: FileCheck,
    title: "Acceptance of Terms",
    paragraphs: [
      "By accessing or using ExamForge AI's website, mobile application, or any of our services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.",
      "If you do not agree with any part of these terms, you must discontinue use of our platform immediately. These terms apply to all visitors, users, and others who access or use our services.",
    ],
  },
  {
    number: "02",
    icon: ShieldCheck,
    title: "Use of Services",
    paragraphs: [
      "You agree to use ExamForge AI's services only for lawful purposes and only as authorized by these Terms. Our platform is designed exclusively for educational purposes — specifically AI-powered exam preparation, study material generation, and performance analytics.",
      "You must not use our services to distribute, share, or reproduce any content generated by ExamForge AI for commercial purposes without prior written consent. Any unauthorized use, including but not limited to automated scraping, data harvesting, or redistribution, is strictly prohibited.",
      "We reserve the right to suspend or terminate your access to our services if we determine, at our sole discretion, that you have violated these terms.",
    ],
  },
  {
    number: "03",
    icon: UserCog,
    title: "User Accounts",
    paragraphs: [
      "When you create an account with ExamForge AI, you are responsible for maintaining the confidentiality of your login credentials, including your password. You agree to accept responsibility for all activities that occur under your account.",
      "You must provide accurate, current, and complete information during the registration process and keep your account information updated. If you suspect any unauthorized use of your account, you must notify us immediately at support@examforge.ai.",
      "ExamForge AI reserves the right to disable any user account at any time if, in our opinion, you have failed to comply with any provision of these Terms of Service.",
    ],
  },
  {
    number: "04",
    icon: Lock,
    title: "Intellectual Property",
    paragraphs: [
      "All content, features, and functionality on ExamForge AI — including but not limited to text, graphics, logos, icons, images, audio clips, AI-generated study materials, questions, and software — are the exclusive property of ExamForge AI and are protected by international copyright, trademark, and other intellectual property laws.",
      "Users retain ownership of the original content they upload to the platform (e.g., textbooks, notes). However, by uploading content, you grant ExamForge AI a non-exclusive, royalty-free license to process, analyze, and generate derivative study material from your content for the purpose of providing our services.",
    ],
  },
  {
    number: "05",
    icon: AlertTriangle,
    title: "Limitation of Liability",
    paragraphs: [
      "ExamForge AI and its directors, employees, partners, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use our services.",
      "Our platform provides AI-generated study materials and practice questions for educational support. We do not guarantee exam success or the accuracy of all generated content. Users should use our services as a supplementary study tool and verify critical information independently.",
      "In no event shall ExamForge AI's total liability exceed the amount you have paid to us in the twelve (12) months preceding the claim.",
    ],
  },
  {
    number: "06",
    icon: RefreshCw,
    title: "Changes to Terms",
    paragraphs: [
      "ExamForge AI reserves the right to modify or replace these Terms of Service at any time, at our sole discretion. When we make material changes, we will notify you by updating the \"Last updated\" date at the top of this page and, where appropriate, provide additional notice via email or in-app notification.",
      "Your continued use of our platform after any changes to the Terms constitutes your acceptance of the new Terms. We encourage you to review these Terms periodically to stay informed about our practices.",
    ],
  },
];

export default function TermsOfServicePage() {
  return (
    <PageLayout
      title="Terms of Service"
      description="Please read these terms carefully before using ExamForge AI."
      breadcrumb={[{ label: "Terms of Service", href: "/terms-of-service" }]}
    >
      <div className="layout-container max-w-[900px] px-4 mx-auto space-y-10">
        {/* Last Updated + Intro */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="bg-white/70 backdrop-blur-xl border border-[#ECECEC] rounded-[24px] p-8 md:p-10 shadow-lg"
        >
          <div className="inline-block bg-[#6D4AFF]/5 text-[#6D4AFF] text-xs font-black uppercase tracking-widest px-4 py-2 rounded-full border border-[#6D4AFF]/10 mb-6">
            Last updated: 25 May 2024
          </div>
          <p className="text-neutral-600 font-medium leading-relaxed">
            Welcome to ExamForge AI. These Terms of Service (&quot;Terms&quot;) govern your access to
            and use of the ExamForge AI platform, including our website, mobile applications, APIs, and
            all related services. By creating an account or using any part of our service, you agree to
            be bound by these Terms and our Privacy Policy.
          </p>
        </motion.div>

        {/* Sections */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.05 }}
          className="space-y-6"
        >
          {sections.map((section, idx) => {
            const Icon = section.icon;
            return (
              <motion.div
                key={idx}
                variants={itemVariants}
                className="bg-white/70 backdrop-blur-xl border border-[#ECECEC] rounded-[24px] p-8 md:p-10 shadow-lg hover:shadow-xl transition-shadow duration-300"
              >
                <div className="flex items-start gap-5 mb-6">
                  <div className="w-12 h-12 rounded-2xl bg-[#6D4AFF]/5 border border-[#6D4AFF]/10 flex items-center justify-center flex-shrink-0">
                    <Icon className="w-6 h-6 text-[#6D4AFF]" />
                  </div>
                  <div>
                    <span className="text-xs font-black text-[#6D4AFF] tracking-widest">
                      SECTION {section.number}
                    </span>
                    <h2 className="text-xl font-black text-neutral-900 mt-1">{section.title}</h2>
                  </div>
                </div>

                <div className="space-y-4 pl-0 md:pl-[68px]">
                  {section.paragraphs.map((paragraph, pIdx) => (
                    <p key={pIdx} className="text-sm font-medium text-neutral-500 leading-relaxed">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </motion.div>
            );
          })}
        </motion.div>
      </div>
    </PageLayout>
  );
}
