"""
ExamForge AI — Response Formatter & Source Attribution
========================================================

Post-processes and formats raw LLM output into a structured, educational tutor response.
Appends source attribution metadata (Task 8) with document name, chapter, score, and resource type.
"""

from __future__ import annotations

import logging
from textwrap import dedent
from typing import Any, List, Dict

logger = logging.getLogger(__name__)


class ResponseFormatter:
    """
    Formats AI responses into structured educational modules and attaches source attributions.
    """

    @classmethod
    def format_response(
        cls,
        raw_answer: str,
        intent: str,
        confidence: str,
        sources: List[Dict[str, Any]],
    ) -> str:
        """
        Format the LLM answer with structured sections and source attributions.

        Parameters
        ----------
        raw_answer:
            The direct text generated by the LLM.
        intent:
            Detected user intent.
        confidence:
            Retrieval confidence: 'high', 'medium', 'low', or 'none'.
        sources:
            List of source metadata dicts from ConfidenceScorer / SearchService.

        Returns
        -------
        str
            Formatted markdown response string.
        """
        cleaned_answer = raw_answer.strip()
        if not cleaned_answer:
            return "I couldn't generate an answer from the uploaded resources."

        # If answer is already structured or formatted (e.g. MCQ JSON or Markdown headings), assemble nicely
        sections: List[str] = [cleaned_answer]

        # Attach Source Attribution block (Task 8)
        attribution_block = cls._build_source_attribution_block(sources, confidence)
        if attribution_block:
            sections.append(attribution_block)

        return "\n\n".join(sections)

    @classmethod
    def _build_source_attribution_block(
        cls,
        sources: List[Dict[str, Any]],
        confidence: str,
    ) -> str:
        """
        Build Task 8 Source Attribution block:
        Includes Document Title, Chapter, Page, Similarity Score, and Resource Type.
        """
        if not sources:
            return ""

        conf_emoji = "🟢" if confidence == "high" else ("🟡" if confidence == "medium" else "🔴")
        lines = [
            "---",
            f"### 📚 Verified Sources ({conf_emoji} Confidence: {confidence.upper()})",
        ]

        seen_sources = set()
        for idx, src in enumerate(sources, start=1):
            title = src.get("document_title") or "Uploaded Document"
            chapter = src.get("chapter") or "General Chapter"
            page = src.get("page_number") or "-"
            score = src.get("score") or 0.0
            res_type = src.get("resource_type") or "Document"

            source_key = f"{title}-{chapter}-{page}"
            if source_key in seen_sources:
                continue
            seen_sources.add(source_key)

            lines.append(
                f"- **[{res_type.upper()}]** *{title}* — Chapter: `{chapter}` | Page: `{page}` (Match Score: `{score:.2f}`)"
            )

        return "\n".join(lines)
